### ISSUE TITLE
question: duplicate folders

### ISSUE THREAD

**Issue by azinsharaf** [itaysharir/Dotfiles#3]
thank you for sharing your great dot files.

I noticed that there are some duplicate and nested folders there. Is it by design?
![image](https://user-images.githubusercontent.com/10101468/209230591-accef6d9-940b-4e71-8a8c-1aae2f1a4cbd.png)

**Comment by itaysharir** [comment]
Sorry for the REALLY late reply, i forgot to check this repo for issues, but it was because i accidentally copied some folders to the wrong directory, i fixed it

**Comment by azinsharaf** [comment]
thanks for checking this but it seems the issue still there:

https://github.com/itaysharir/Dotfiles/tree/main/config/rices/dt-xmonad/skhd/skhd/skhd/skhd
